# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3ab2ba39586befe9757f7280f30dacf1f34e843cc6db3f1bf46953590eff945509d9b561be09419a84e7874f2abfe12fdada900d2c5de653e613d9a32a34dbc

test:
  secret_key_base: 175c1fd4246a09852e1bf468435b2fadb5eeeabfcf0e1548d8b69e1b4c9630757bf89bc7465913b9f7919b52e5f1d3df4f8d813d59da0f88cdd2f404777ed23b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
